---
deployment:
  tasks:
    - export DEPLOYPATH=/home/peiozerb/sites/prueba.peio.zerbitzaria.net
    - rm -Rf $DEPLOYPATH/* 
    - cp -Rf model $DEPLOYPATH
    - cp -Rf view $DEPLOYPATH
    - cp -Rf controller $DEPLOYPATH
    - cp -Rf index.html $DEPLOYPATH